const poojas = [
  {
    icon: "🔱",
    name: "Mangal Dosh Puja",
    hindi: "मंगल दोष पूजा",
    duration: "2–3 Hours",
    price: "₹1,100 / ₹2,100 / ₹5,100 / ₹11,000",
    desc: "Special puja to remove Mangal Dosha with specific Vedic puja and anushthaan.",
  },
  {
    icon: "🐍",
    name: "Kaal Sarp Dosh Puja",
    hindi: "कालसर्प दोष पूजा",
    duration: "3–4 Hours",
    price: "₹2,100 / ₹3,500",
    desc: "Powerful Vedic puja to remove Kaal Sarp Dosha and its afflictions.",
  },
  {
    icon: "🕉️",
    name: "Rudrabhishek",
    hindi: "रुद्राभिषेक",
    duration: "2 Hours",
    price: "₹3,100 / ₹5,100",
    desc: "Abhishek of Shiva with sacred ingredients for blessings and protection.",
  },
  {
    icon: "🪬",
    name: "Mahamrityunjay Jaap",
    hindi: "महामृत्युंजय जाप",
    duration: "6 Hours",
    price: "₹35,000",
    desc: "Powerful chanting for health, longevity and protection from untimely death.",
  },
  {
    icon: "⭐",
    name: "Navgrah Shanti Puja",
    hindi: "नवग्रह शांति पूजा",
    duration: "2–3 Hours",
    price: "₹3,500",
    desc: "Vedic puja to pacify all nine planets and bring harmony and peace.",
  },
  {
    icon: "👴",
    name: "Pitru Dosh Shanti",
    hindi: "पितृ दोष शांति",
    duration: "3 Hours",
    price: "₹3,100",
    desc: "Puja to relieve Pitru Dosha and offer peace and moksha to ancestors.",
  },
  {
    icon: "💍",
    name: "Ark Vivah",
    hindi: "आर्क विवाह",
    duration: "2–3 Hours",
    price: "₹2,500",
    desc: "Sacred ritual for Manglik persons before marriage for auspiciousness.",
  },
  {
    icon: "🫧",
    name: "Kumbh Vivah",
    hindi: "कुम्भ विवाह",
    duration: "2–3 Hours",
    price: "₹2,500",
    desc: "Vedic ritual for Manglik persons to reduce the effect of Mangal Dosha.",
  },
  {
    icon: "🙏",
    name: "Narayan Bali",
    hindi: "नारायणबली",
    duration: "4–5 Hours",
    price: "₹11,000",
    desc: "Important ritual for peace and moksha of ancestors.",
  },
  {
    icon: "🐍",
    name: "Nagbali",
    hindi: "नागबली",
    duration: "4–5 Hours",
    price: "₹11,000",
    desc: "Puja to seek forgiveness from Nag Dev and remove related doshas.",
  },
  {
    icon: "🏠",
    name: "Vastu Puja",
    hindi: "वास्तु पूजा",
    duration: "4 Hours",
    price: "₹7,500",
    desc: "Puja for harmony and positive energy in your home or office.",
  },
  {
    icon: "📿",
    name: "Saptashati Path",
    hindi: "सप्तशती पाठ",
    duration: "2–3 Hours",
    price: "₹3,100",
    desc: "Sacred reading of Durga Saptashati for Devi's protection and blessings.",
  },
];